config:
  target: "http://localhost:3000"
  phases:
    - duration: 30
      arrivalRate: 1
      rampTo: 100
      name: "Warm up the application"
    - duration: 60
      arrivalRate: 100
      name: "Sustained light load"
    - duration: 30
      arrivalRate: 100
      rampTo: 500
      name: "Warm up to max load"
    - duration: 60
      arrivalRate: 500
      name: "Sustained max load"
  payload:
    - path: "./csv/favorites.csv"
      fields:
        - "tweet_id"
        - "favoriter_id"
        - "author_id"
        - "favorite_count"
        - "user_favorites_count"
        - "destroy"
    - path: "./csv/feeds.csv"
      fields:
        - "user_id"
        - "count_id"
    - path: "./csv/follows.csv"
      fields:
        - "follower_id"
        - "friends_count"
        - "followers_count"
        - "followed_id"
        - "destroy"
    - path: "./csv/tweets.csv"
      fields:
        - "user_id"
        - "status"
        - "source"
scenarios:
  - name: "Favorite a tweet"
    flow:
      - post:
          url: "/favorite"
          json:
            tweet_id: '{{ tweet_id }}'
            favoriter_id: '{{ favoriter_id }}'
            author_id: '{{ author_id }}'
            favorite_count: '{{ favorite_count }}'
            user_favorites_count: '{{ user_favorites_count }}'
            destroy: '{{ destroy }}'
  - name: "View feed"
    flow:
      - get:
          url: "/feed"
          query:
            user_id: '{{ user_id }}'
            count_id: '{{ count_id }}'
  - name: "Follow a user"
    flow:
      - post:
          url: "/follow"
          json:
            follower_id: '{{ follower_id }}'
            friends_count: '{{ friends_count }}'
            followers_count: '{{ followers_count }}'
            followed_id: '{{ followed_id }}'
            destroy: '{{ destroy }}'
  - name: "Write Tweet"
    flow:
      - post:
          url: "/tweets"
          json:
            user_id: '{{ user_id }}'
            status: '{{ status }}'
            source: '{{ source }}'