// an example tweet object that might appear in a feed array

{
  [
    {
      "truncated": false,
      "created_at": "Tue Aug 28 21:08:15 +0000 2012",
      "favorited": false,
      "id_str": "240556426106372096",
      "in_reply_to_user_id_str": null,
      "text": "lecturing at the \"analyzing big data with twitter\" class at @cal with @othman  http://t.co/bfj7zkDJ",
      "contributors": null,
      "id": 240556426106372096,
      "retweet_count": 3,
      "in_reply_to_status_id_str": null,
      "retweeted": false,
      "possibly_sensitive": false,
      "in_reply_to_user_id": null,
      "source": "Safari on iOS",
      "user": {
        "name": "Raffi Krikorian",
        "profile_sidebar_fill_color": "DDEEF6",
        "profile_background_tile": false,
        "profile_sidebar_border_color": "C0DEED",
        "profile_image_url": "http://a0.twimg.com/profile_images/1270234259/raffi-headshot-casual_normal.png",
        "created_at": "Sun Aug 19 14:24:06 +0000 2007",
        "location": "San Francisco, California",
        "id_str": "8285392",
        "is_translator": false,
        "profile_link_color": "0084B4",
        "default_profile": true,
        "url": "http://t.co/eNmnM6q",
        "contributors_enabled": false,
        "favorites_count": 724,
        "utc_offset": -28800,
        "profile_image_url_https": "https://si0.twimg.com/profile_images/1270234259/raffi-headshot-casual_normal.png",
        "id": 8285392,
        "listed_count": 619,
        "profile_use_background_image": true,
        "profile_text_color": "333333",
        "followers_count": 18752,
        "lang": "en",
        "protected": false,
        "description": "Director of @twittereng's Platform Services. I break things.",
        "profile_background_color": "C0DEED",
        "verified": false,
        "time_zone": "Pacific Time (US & Canada)",
        "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme1/bg.png",
        "statuses_count": 5007,
        "profile_background_image_url": "http://a0.twimg.com/images/themes/theme1/bg.png",
        "default_profile_image": false,
        "friends_count": 701,
        "following": true,
        "show_all_inline_media": true,
        "screen_name": "raffi"
      },
      "in_reply_to_screen_name": null,
      "in_reply_to_status_id": null
    },
  ];
}